### ISSUE TITLE
ADD ability to search for submenus without specifying parent menu

### ISSUE THREAD

**Issue by allanlaal** [singhleo/admin-menus-accessibility#4]
use case:
not knowing what parent they are under, usually the reason for searching something ;)

**Comment by singhleo** [comment]
Hey Allan,
You don't need to specify parent menu. just type anything if it's present as submenu/parent it will appear.
Eg.
![image](https://user-images.githubusercontent.com/2202041/45349985-68bf6980-b5d0-11e8-8b13-923c8e6e15a7.png)
